### ISSUE TITLE
SQL Injection vulnerability (scary!)

### ISSUE THREAD

**Issue by fluxehub** [lucidcelestial/awful#1]
The use of string interpolation (such as the below code) leaves the site open to SQL Injection (scary!!! 😟😟😟)

```php
$searchQuery = $_POST['searchQuery'];   
$query = 'select * from product where name like \'%' . $searchQuery . '%\' or manifacturer like \'%' . $searchQuery . '%\' and category = \'Guitars\'';
siteCallWithQuery("Guitars", $query);
```

Using prepared statements like the example below would fix this vulnerability.

```php
$query = $pdo->prepare('select * from product where name like (:query) or manifacturer like (:query) and category = \'Guitars\'');
$query->execute(array('query' => $searchQuery));
```

This would be a huge concern if there was indeed any evidence that those assessing this work even know what a SQL injection is, which is highly unlikely.

**Comment by lucidcelestial** [comment]
![image](https://github.com/lucidcelestial/awful/assets/100162902/99b62119-39b3-43d6-9b6e-538a8179d58d)

**Comment by lucidcelestial** [comment]
( wouldn't have been graded idt but i fixed it anyways )

**Comment by fluxehub** [comment]
ngl i didn't actually expect you to fix it cause like who cares lmao, but this is actually a good implementation looking at the code. I will ignore the comment in the code 😁

![](https://user-images.githubusercontent.com/100162902/277097813-99b62119-39b3-43d6-9b6e-538a8179d58d.png)
